### ISSUE TITLE
Attack cooldown timer not working

### ISSUE THREAD

**Issue by CapClumsy** [CapClumsy/emubot#11]
https://github.com/CapClumsy/emubot/blob/a504dd2b551119cd8ce2f396f553133507979a64/Emubot_master_file.py#L33-L34
https://github.com/CapClumsy/emubot/blob/a504dd2b551119cd8ce2f396f553133507979a64/Emubot_master_file.py#L279-L343
These are all the lines of code related to the attack cooldown. I don't know why it is happening.

**Comment by Beastkin** [comment]
Why isn't this working?

**Comment by CapClumsy** [comment]
Read the above comment's last line. "These are all the lines of code related to the attack cooldown. I don't know why it is happening."
### " I don't know why this is happening."

**Comment by Beastkin** [comment]
Oh lit bro

**Comment by CapClumsy** [comment]
### Proposed Solution
In line 338 (of the above code) it says `attacktimer1(message.author.id)`, where it *should* say `attacktimer1(message.author.id) = False`, as it is just stating a variable instead of changing the value of a variable.

**Comment by Beastkin** [comment]
litty then change it

**Comment by CapClumsy** [comment]
Actually, I believe that the solution is changing line 283 from 
`if (message.author.id in attacktimer1) or (not message.author.id in attacktimer1 and attacktimer1[message.author.id]):`
to:
`if (message.author.id in attacktimer1)  and (attacktimer1[message.author.id]): `

**Comment by CapClumsy** [comment]
This commit does fix it, it `attacktimer1` does switch back to `false` when it should.
